### ISSUE TITLE
'Aeson exception: key "pluginTimeout" not present' when running example code

### ISSUE THREAD

**Issue by ThatsNoMoon** [saevarb/haskord#1]
Log:
```
Aeson exception:
Error in $: key "pluginTimeout" not present
```
Code is copy-pasted from the example, with commit `c0fcc6413ec07be961adba8db960d6ab0252382e` used for the Haskord package in `stack.yaml`

**Comment by saevarb** [comment]
Sorry for the late reply -- you'd probably be better off asking me in the FP server for a quicker response.

I've been developing the bot faster than the docs. The `pluginTimeout` in the config determines how many seconds plugins can run before they are killed. So your config should just look something like

```yaml
botToken: <your token>
pluginTimeout: 15
```

Unfortunately, the haskell eval plugin can be really slow to run depending on how beefy the machine is that's running the bot, so I'd recommend at least 15 seconds.

**Comment by ThatsNoMoon** [comment]
No problem, and thanks for the clarification
